import type { AIInsightsResponse } from "../types/ai";

interface Props {
  insights: AIInsightsResponse;
}

interface SectionProps {
  icon: string;
  title: string;
  content: string;
}

function InsightSection({
  icon,
  title,
  content,
}: SectionProps) {
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50 p-6 transition hover:border-blue-300 hover:shadow-sm">
      <div className="flex items-center gap-3">
        <span className="text-2xl">{icon}</span>

        <h3 className="text-xl font-semibold text-slate-900">
          {title}
        </h3>
      </div>

      <p className="mt-4 leading-8 text-slate-700">
        {content}
      </p>
    </div>
  );
}

export default function AIInsightsCard({
  insights,
}: Props) {
  return (
    <section className="rounded-3xl border border-slate-200 bg-white p-8 shadow-lg">

      <div className="flex items-center gap-4 border-b border-slate-200 pb-6">

        <div className="flex h-16 w-16 items-center justify-center rounded-full bg-blue-100 text-3xl">
          🤖
        </div>

        <div>
          <h2 className="text-3xl font-bold text-slate-900">
            AI Biological Insights
          </h2>

          <p className="mt-1 text-slate-600">
            AI-generated interpretation based on curated biological annotations.
          </p>
        </div>

      </div>

      <div className="mt-8 space-y-6">

        <InsightSection
          icon="🧬"
          title="Overview"
          content={insights.overview}
        />

        <InsightSection
          icon="⚙️"
          title="Biological Role"
          content={insights.biological_role}
        />

        <InsightSection
          icon="🦠"
          title="Disease Relevance"
          content={insights.disease_relevance}
        />

        <InsightSection
          icon="💊"
          title="Therapeutic Potential"
          content={insights.therapeutic_potential}
        />

        <InsightSection
          icon="📚"
          title="Research Highlights"
          content={insights.research_highlights}
        />

      </div>

      <div className="mt-8 rounded-xl bg-blue-50 p-5">

        <p className="text-sm text-slate-700">
          <span className="font-semibold">
            Generated by Gene Insight Explorer AI
          </span>
        </p>

        <p className="mt-2 text-sm text-slate-600">
          This summary is automatically generated from curated biological
          annotations and should be used for research and educational
          purposes.
        </p>

      </div>

    </section>
  );
}